name = "StripRTF"
uuid = "221a10cb-40ed-42a6-9d60-e07216d033df"
authors = ["Steven G. Johnson <stevenj@alum.mit.edu> and contributors"]
version = "1.1.0"

[deps]
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
julia = "1.4"
StringEncodings = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
